{
  "hash": "1b6b321963e8e84cb35b784c4ffe164d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Temporal Analysis of Road Crashes in the Australian Capital Territory\"\nauthor: \"Thomas Martin\"\ndate: \"02 December, 2025\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Introduction\n\nEvery day in the Australian Capital Territory (ACT), it is estimated that there are nearly 1 million car trips [2]. Unfortunately, a small proportion of those daily car trips end in accidents. This report will apply various time series modelling approaches to model the number of daily road crashes in the ACT from the 1 January 2015 to 31 December 2019. The aim of the report is to determine the best estimation technique to produce the most accurate prediction of ACT daily car crashes. The resulting model can be applied to predict the trend in future car crashes in the ACT as well as understand patterns in the prevalence of road accidents in the ACT.\nThe data used for this report was collected by the AFP Crash Report Form, and collected from the ACT Open Data Portal as at 30 April 2025 [1]. All crashes in the ACT must be reported to police within 24 hours, unless attended by police [3]. It is worth noting then, that this may under report serious road accidents, which would likely be attended by police. Therefore, we are likely measuring moderate and minor road accidents. This includes all crashes by users, drivers, cyclists, pedestrians and motorcyclists on roads, paths and other road related areas involving pedestrians or cyclists. All crash incidents are aggregated by day to transform the dataset into a daily time series. Therefore, the time series measures daily road crashes in the ACT reported through the AFP crash report system, hereafter referred to as ACT road crashes. This report limited the timeline of the data from 2015 to 2019 to model the data without the presence of the COVID lockdowns skewing the result. \n\n\n::: {.cell}\n\n:::\n\n\n# Data Characteristics\n\n\nWe will refer to the number of car crashes as $y_t$, where $t = 1, 2, ..., 1825, 1826$. The first day of data is 1 January 2015 and the last day is 31 December 2019.\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nObserving the histogram of ACT daily road crashes, we observe that the distribution has a longer right tail suggesting the data is slightly right skewed. This suggests that the data is likely Poisson distributed, however it is not dissimilar to a normal distribution so linear regression may still be appropriate for modelling this data.\n\n\n::: {.cell figfig-cap='Daily Number of Reported ACT Road Crashes 2015 to 2019'}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/fig-tsplot-1.png){#fig-tsplot width=672}\n:::\n:::\n\nWe observe several patterns from the time series graph above.  The mean of the time series depends on time, with overall a slight decrease in the second half of the time series. This creates a challenge as the model will be trained on the first half of the data set only which appears to in fact have a stationary mean. This is unavoidable though as the test data set is treated as unobserved for the purposes of the modelling. Therefore, from here on out the EDA will focus on the  $1 \\ldots T$ time points as this will guide later model selection. Certain periods in the dataset have decreased variance such as January, which signals the presence of non-constant variance. There is evidence of seasonality, once again around January there is a drop in the number of road crash reports and when you look at a more mirco level there is some obvious weekly seasonality.\n\n\n::: {.cell}\n\n:::\n\n\nWe will split the data into train and test such that T = 912 and T' = 913, meaning that the first day of the test dataset is 1 July 2017. We will split the data into train and test such that $T = 912$ and $T' = 913$, meaning that the first day of the test dataset is 1 July 2017. First, we use a Box-Cox test to find the best value of $\\lambda = 0.4727$to stabilise the variance, this is done first as per Hyndamyn [8]. All following time series methods will be applied to this variance stabilize time series $z_t = y_t^{\\frac{1}{2}} - 1$. This procedure stabilized the variance of $z_t$, the time series graphs showing this are in see Appendix B. They show that the transformed training data set had a stationary mean, relatively stationary variance however, seasonality is still prevalent. The ACF shows strong correlation at lag 7 and the PACF shows decaying partial correlation at lag 7 (in addition to other lags), which strongly suggests weekly seasonality. Note that yearly seasonality (364 days) was also considered as a possibility however, calendar considerations make this a tricky periodicity to difference at.\n\n\n::: {.cell figfig-cap='Square Root Transformed and First Differenced Daily Number of Reported ACT Road Crashes 2015 to 2019'}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/fig-boxcox-d1-1.png){#fig-boxcox-d1 width=672}\n:::\n:::\n\n\n\n\n## Seasonal Components\nMy prior going into this analysis, is that road crashes will occur more frequently on days where there is the greatest volume of driving. This may run slightly contrary  to intuition which may be that long weekends have more accidents however, it is likely that there are more fatal accidents from long car drives rather than road crashes which is what we are attempting to measure. In the ACT, I hypothesize that workdays are the busiest days on the road as workers are commuting to work, businesses are receiving and sending deliveries and parents are taking their children to school. Therefore, I would expect that the ACT road crashes would vary depending on the day of the week, school holidays, public holidays, when workers tend to take leave and potentially the month of the year. I was able to use the ACT government website to get past information for public holidays and public school holidays [5, 6].\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAs hypothesized, there is a strong pattern in the weekday data where Saturday and Sunday have the least crashes. The month plot mostly shows a significant difference only for January and maybe a slight difference for December. Holidays plot shows strong reduction in crashes, particularly for public holidays. These factors should be considered in a time-trend model.\n\n# Model Fitting and Interpretation\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 estimate     se p.values\n(Intercept)                        3.5402 0.1191   0.0000\nday2Sat                           -0.7205 0.0811   0.0000\nday2Sun                           -1.2200 0.0768   0.0000\nday2Thu-Fri                        0.3285 0.0692   0.0000\nday2Tue-Wed                        0.2291 0.0732   0.0018\nmonth2Apr-May                      0.4536 0.1046   0.0000\nmonth2Aug-Oct                      0.3564 0.1048   0.0007\nmonth2Dec                          0.1505 0.1833   0.4116\nmonth2Feb                          0.1832 0.1215   0.1316\nmonth2Jul                          0.4917 0.1013   0.0000\nmonth2Jun                          0.3640 0.1316   0.0057\nmonth2Mar                          0.3702 0.1218   0.0024\nmonth2Nov                          0.1801 0.1259   0.1525\nholidayPublic and School Holiday  -1.9650 0.1148   0.0000\nholidayPublic Holiday             -1.9895 0.2405   0.0000\nholidaySchool Holiday             -0.5674 0.0821   0.0000\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.069435\n```\n\n\n:::\n:::\n\n\n## Time Trend Model\n\nFirst, we will attempt to fit a linear time trend model to the transformed training data $z_t$. Note, a Poisson model was attempted on the untransformed data as the data is Poisson distributed however, the linear model fit on the transformed data was superior. The first model fit was: $M_1:z_t=β_0  + β_1 t_i+β_(2-7) day_i+β_(8-19) month_i+β_(20-23) holiday_i+ \\nu_i$. Note that I chose not to fit cyclical day of week and month factors, this is because there is enough observations (912) to fit the more descriptive factor variables and, the marginal trend wasn’t particularly cyclical. This model had some day and months with similar marginal associations and time variables were insignificant, as expected from the trend plots. Days were grouped instead as: Sun, Mon, Tue-Wed, Thu-Fri and Sat and months as: Jan, Feb, Mar, Apr-May, June, July, Aug-Oct, Nov and Dec. A new model was fit with these reduced categories and the time factor removed: $M_2:z_t=β_0+β_(1-4) da〖y2〗_i+β_(5-12) month_i+β_(13-15) holiday_i+ \\nu_i$. An Anova test was performed to see if any explanatory power was lost. The p-value of the test was 0.9997, so we failed to reject the null and find no evidence that the additional variables in M_1 are non-zero, and choose the model M_2.\n\n$$\nM_2 : z_t = 3.5402 (0.1191)-0.7205 (0.0811)Sat -1.2200 (0.0768) Sun + 0.3285 (0.0692) \\text{Thu-Fri} + 0.2291 (0.0732) \\text{Tue-Wed}+0.4536 (0.1046) \\text{Apr-May} +0.3564 (0.1048) \\text{Aug-Oct} +0.1505 (0.1833) Dec+0.1832 (0.1215) Feb+0.4917 (0.1013) Jul+0.3640 (0.1316) Jun+0.3702 (0.1218) Mar + 0.1801 (0.1259) Nov - 1.9650 (0.1148) \\text{Public and School Holiday}-1.9895 (0.2405) \\text{Public Holiday} -0.5674 (0.0821) \\text{School Holiday} +  \\nu_t\n$${#eq-M2}\n\nWe observe that Saturday and Sunday see a large negative marginal association with road crashes, whilst Monday has a positive marginal association, whilst holding all other variable constant. The day of the week being Sunday compared to Monday, is associated with a 1.200 decrease in the square root of the number of ACT Road crashes, holding all other variables constant. So it seems that there are less road crashes on the weekend (Saturday has a similar affect). The month of January stands out as having a large negative marginal association with ACT road crashes and school and public holiday have large negative marginal associations, in particular the public holidays have an association that is approximately three times larger than the school holidays. A public holiday compared to a non-public or school holiday day, is associated with a 1.9895 decrease in the square root of the number of  ACT road crashes, holding all other variables constant. Note that $z_t$ is sqrt transformed when interpreting the above coefficients. An analysis of the residuals shows that the variance has stabilised, however there appears to be some serial autocorrelation of the residuals, potentially of the MA(1) order. These plots are available in the appendix. In addition, due to this dependence of errors, sandwich HAC errors were used for the standard estimates, a full regression output table is in Table C. To remove serial autocorrelation, lets use some ARMA models to model the residuals.\n\n::: callout-note\n## Time Series Display for Time Trend Model (optional)\n<details>\n<summary>Click to expand time series diagnostic display</summary>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nAs above, the residuals appear to demonstrate MA(1) autocorrelation.\n\n</details>\n:::\n\n\n## Time Trend with ARMA(0, 1) Residuals (SEACF)\n\nThe ACF and PACF plot provide weak evidence of a simple ARMA(0, 1) trend in the residuals $\\nu_t$. Lets perform a SEACF plot to estimate the order of an ARMA model fitted to these time-trend residuals, with a maximum order of p = 14 and q = 20.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kpeazvgeew\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kpeazvgeew table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kpeazvgeew thead, #kpeazvgeew tbody, #kpeazvgeew tfoot, #kpeazvgeew tr, #kpeazvgeew td, #kpeazvgeew th {\n  border-style: none;\n}\n\n#kpeazvgeew p {\n  margin: 0;\n  padding: 0;\n}\n\n#kpeazvgeew .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kpeazvgeew .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kpeazvgeew .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kpeazvgeew .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kpeazvgeew .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kpeazvgeew .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kpeazvgeew .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kpeazvgeew .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kpeazvgeew .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kpeazvgeew .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kpeazvgeew .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kpeazvgeew .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kpeazvgeew .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kpeazvgeew .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kpeazvgeew .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpeazvgeew .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kpeazvgeew .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kpeazvgeew .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kpeazvgeew .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpeazvgeew .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kpeazvgeew .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpeazvgeew .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kpeazvgeew .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpeazvgeew .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kpeazvgeew .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpeazvgeew .gt_left {\n  text-align: left;\n}\n\n#kpeazvgeew .gt_center {\n  text-align: center;\n}\n\n#kpeazvgeew .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kpeazvgeew .gt_font_normal {\n  font-weight: normal;\n}\n\n#kpeazvgeew .gt_font_bold {\n  font-weight: bold;\n}\n\n#kpeazvgeew .gt_font_italic {\n  font-style: italic;\n}\n\n#kpeazvgeew .gt_super {\n  font-size: 65%;\n}\n\n#kpeazvgeew .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kpeazvgeew .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kpeazvgeew .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kpeazvgeew .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kpeazvgeew .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kpeazvgeew .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kpeazvgeew .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kpeazvgeew .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kpeazvgeew div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"22\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Extended Autocorrelation Function (EACF)</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"AR-order\">AR order</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a0\">0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a2\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a3\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a4\">4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a5\">5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a6\">6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a7\">7</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a8\">8</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a9\">9</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a10\">10</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a11\">11</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a12\">12</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a13\">13</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a14\">14</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a15\">15</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a16\">16</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a17\">17</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a18\">18</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a19\">19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a20\">20</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">0</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">o</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">o</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">1</td>\n<td headers=\"0\" class=\"gt_row gt_left\">o</td>\n<td headers=\"1\" class=\"gt_row gt_left\">o</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">o</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">2</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">o</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">o</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">3</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">o</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">4</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">5</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">6</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">x</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">7</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">x</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">x</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">8</td>\n<td headers=\"0\" class=\"gt_row gt_left\">o</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">x</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">x</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">9</td>\n<td headers=\"0\" class=\"gt_row gt_left\">o</td>\n<td headers=\"1\" class=\"gt_row gt_left\">o</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">x</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">x</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">10</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">x</td>\n<td headers=\"6\" class=\"gt_row gt_left\">x</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">o</td>\n<td headers=\"10\" class=\"gt_row gt_left\">o</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">11</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">x</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">x</td>\n<td headers=\"9\" class=\"gt_row gt_left\">x</td>\n<td headers=\"10\" class=\"gt_row gt_left\">x</td>\n<td headers=\"11\" class=\"gt_row gt_left\">o</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">12</td>\n<td headers=\"0\" class=\"gt_row gt_left\">x</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">x</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">x</td>\n<td headers=\"10\" class=\"gt_row gt_left\">x</td>\n<td headers=\"11\" class=\"gt_row gt_left\">x</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">13</td>\n<td headers=\"0\" class=\"gt_row gt_left\">o</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">o</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">o</td>\n<td headers=\"5\" class=\"gt_row gt_left\">o</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">x</td>\n<td headers=\"10\" class=\"gt_row gt_left\">x</td>\n<td headers=\"11\" class=\"gt_row gt_left\">x</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n    <tr><td headers=\"AR order\" class=\"gt_row gt_right\">14</td>\n<td headers=\"0\" class=\"gt_row gt_left\">o</td>\n<td headers=\"1\" class=\"gt_row gt_left\">x</td>\n<td headers=\"2\" class=\"gt_row gt_left\">x</td>\n<td headers=\"3\" class=\"gt_row gt_left\">x</td>\n<td headers=\"4\" class=\"gt_row gt_left\">x</td>\n<td headers=\"5\" class=\"gt_row gt_left\">x</td>\n<td headers=\"6\" class=\"gt_row gt_left\">o</td>\n<td headers=\"7\" class=\"gt_row gt_left\">o</td>\n<td headers=\"8\" class=\"gt_row gt_left\">o</td>\n<td headers=\"9\" class=\"gt_row gt_left\">x</td>\n<td headers=\"10\" class=\"gt_row gt_left\">x</td>\n<td headers=\"11\" class=\"gt_row gt_left\">x</td>\n<td headers=\"12\" class=\"gt_row gt_left\">o</td>\n<td headers=\"13\" class=\"gt_row gt_left\">o</td>\n<td headers=\"14\" class=\"gt_row gt_left\">o</td>\n<td headers=\"15\" class=\"gt_row gt_left\">o</td>\n<td headers=\"16\" class=\"gt_row gt_left\">o</td>\n<td headers=\"17\" class=\"gt_row gt_left\">o</td>\n<td headers=\"18\" class=\"gt_row gt_left\">o</td>\n<td headers=\"19\" class=\"gt_row gt_left\">o</td>\n<td headers=\"20\" class=\"gt_row gt_left\">o</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe largest triangle of zeros supports the idea that an ARMA(0, 1) model is a good choice. Note that ARMA(1, 1) is another interesting choice, however you lose the top row of 0’s, in exchange for a diagonal of 0’s with one X. Therefore, the ARMA(0, 1) is the preferred vertex point, so lets fit this model using Maximum Likelihood estimation and without a mean because the time trend model already contains a mean.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     estimate         se     p.values\nma1 0.1673439 0.03224942 2.113688e-07\n```\n\n\n:::\n:::\n\n\nThe formula for the ARMA(0,1) model is: $\\nu_t=0.1672(0.03226) \\epsilon_{t-1}+ \\epsilon_t$. And then the final time trend model with ARMA(0,1) residuals is:\n\n$$\n\\begin{aligned}\nz_t= 3.5402 (0.1191)- 0.7205 (0.0811) Sat - 1.2200 (0.0768) Sun + 0.3285 (0.0692) \\text{Thu-Fri} \\\\\n+ 0.2291 (0.0732) \\text{Tue-Wed}+0.4536 (0.1046) \\text{Apr-May}+0.3564 (0.1048) \\text{Aug-Oct} \\\\ \n+0.1505 (0.1833) \\text{Dec} + 0.1832 (0.1215) \\text{Feb}+0.4917 (0.1013) \\text{Jul} \\\\\n + 0.3640 (0.1316) \\text{Jun}+0.3702 (0.1218) \\text{Mar}+0.1801 (0.1259) \\text{Nov} \\\\\n -1.9650 (0.1148) \\text{Public and School Holiday}-1.9895 (0.2405) \\text{Public Holiday} \\\\\n -0.5674 (0.0821) \\text{School Holiday} +  0.1672 (0.03226) \\epsilon_{t-1} + \\epsilon_t\n\\end{aligned}\n$${#eq-M3}\n\nOverall, the interpretation of this model is the same as the time-trend model but without serial autocorrelation. We estimate that the error of the time-trend model follows a moving average ARMA(0, 1) process, however this is the only additional interpretation we can make.  No linear trend with time exists in the data, and the fluctuations appear to mostly be driven by seasonal trends and public holidays.\n\n\n## Time Trend with ARMA(1, 0) Residuals (AIC)\n\nIn addition to the SEACF, lets also try another order estimation technique for $\\nu_t$. Particularly as the SEACF plot was not definite on the best vertex choice. Instead, we will fit all combinations of ARMA(p, q) up to order 7, and find the model with the smallest Alkaline Information Criteria (AIC). 7 is used as the maximum order as strong seasonality at this order was detected and the SEACF indicates the best choice is somewhere in this range. The table of fitted AIC is below in @tbl-tt-aic, the smallest AIC was found for the ARMA(1, 0) model with an AIC of 1734.405. This was closely followed by ARMA(0, 1) model with AIC of 1734.747. \n\n::: {#tbl-tt-aic .cell tbl-cap='Estimated AIC of Time Trend model with different ARMA models for modelling the residuals. Rows contain order of p, columns contain order of q.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"leselonkuq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#leselonkuq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#leselonkuq thead, #leselonkuq tbody, #leselonkuq tfoot, #leselonkuq tr, #leselonkuq td, #leselonkuq th {\n  border-style: none;\n}\n\n#leselonkuq p {\n  margin: 0;\n  padding: 0;\n}\n\n#leselonkuq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#leselonkuq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#leselonkuq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#leselonkuq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#leselonkuq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#leselonkuq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#leselonkuq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#leselonkuq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#leselonkuq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#leselonkuq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#leselonkuq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#leselonkuq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#leselonkuq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#leselonkuq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#leselonkuq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#leselonkuq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#leselonkuq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#leselonkuq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#leselonkuq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#leselonkuq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#leselonkuq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#leselonkuq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#leselonkuq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#leselonkuq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#leselonkuq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#leselonkuq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#leselonkuq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#leselonkuq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#leselonkuq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#leselonkuq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#leselonkuq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#leselonkuq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#leselonkuq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#leselonkuq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#leselonkuq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#leselonkuq .gt_left {\n  text-align: left;\n}\n\n#leselonkuq .gt_center {\n  text-align: center;\n}\n\n#leselonkuq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#leselonkuq .gt_font_normal {\n  font-weight: normal;\n}\n\n#leselonkuq .gt_font_bold {\n  font-weight: bold;\n}\n\n#leselonkuq .gt_font_italic {\n  font-style: italic;\n}\n\n#leselonkuq .gt_super {\n  font-size: 65%;\n}\n\n#leselonkuq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#leselonkuq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#leselonkuq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#leselonkuq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#leselonkuq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#leselonkuq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#leselonkuq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#leselonkuq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#leselonkuq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a0\">0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a2\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a3\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a4\">4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a5\">5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a6\">6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a7\">7</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_right gt_stub\">0</th>\n<td headers=\"stub_1_1 0\" class=\"gt_row gt_right\">1758.674</td>\n<td headers=\"stub_1_1 1\" class=\"gt_row gt_right\">1734.747</td>\n<td headers=\"stub_1_1 2\" class=\"gt_row gt_right\">1736.361</td>\n<td headers=\"stub_1_1 3\" class=\"gt_row gt_right\">1738.308</td>\n<td headers=\"stub_1_1 4\" class=\"gt_row gt_right\">1739.558</td>\n<td headers=\"stub_1_1 5\" class=\"gt_row gt_right\">1741.195</td>\n<td headers=\"stub_1_1 6\" class=\"gt_row gt_right\">1743.152</td>\n<td headers=\"stub_1_1 7\" class=\"gt_row gt_right\">1744.010</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_right gt_stub\">1</th>\n<td headers=\"stub_1_2 0\" class=\"gt_row gt_right\" style=\"background-color: #00FF00; font-weight: bold;\">1734.405</td>\n<td headers=\"stub_1_2 1\" class=\"gt_row gt_right\">1736.350</td>\n<td headers=\"stub_1_2 2\" class=\"gt_row gt_right\">1738.348</td>\n<td headers=\"stub_1_2 3\" class=\"gt_row gt_right\">1740.207</td>\n<td headers=\"stub_1_2 4\" class=\"gt_row gt_right\">1741.276</td>\n<td headers=\"stub_1_2 5\" class=\"gt_row gt_right\">1743.210</td>\n<td headers=\"stub_1_2 6\" class=\"gt_row gt_right\">1743.349</td>\n<td headers=\"stub_1_2 7\" class=\"gt_row gt_right\">1745.373</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_right gt_stub\">2</th>\n<td headers=\"stub_1_3 0\" class=\"gt_row gt_right\">1736.347</td>\n<td headers=\"stub_1_3 1\" class=\"gt_row gt_right\">1738.352</td>\n<td headers=\"stub_1_3 2\" class=\"gt_row gt_right\">1740.347</td>\n<td headers=\"stub_1_3 3\" class=\"gt_row gt_right\">1739.609</td>\n<td headers=\"stub_1_3 4\" class=\"gt_row gt_right\">1742.354</td>\n<td headers=\"stub_1_3 5\" class=\"gt_row gt_right\">1743.367</td>\n<td headers=\"stub_1_3 6\" class=\"gt_row gt_right\">1744.215</td>\n<td headers=\"stub_1_3 7\" class=\"gt_row gt_right\">1747.080</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_right gt_stub\">3</th>\n<td headers=\"stub_1_4 0\" class=\"gt_row gt_right\">1738.311</td>\n<td headers=\"stub_1_4 1\" class=\"gt_row gt_right\">1739.525</td>\n<td headers=\"stub_1_4 2\" class=\"gt_row gt_right\">1740.112</td>\n<td headers=\"stub_1_4 3\" class=\"gt_row gt_right\">1742.418</td>\n<td headers=\"stub_1_4 4\" class=\"gt_row gt_right\">1738.355</td>\n<td headers=\"stub_1_4 5\" class=\"gt_row gt_right\">1744.476</td>\n<td headers=\"stub_1_4 6\" class=\"gt_row gt_right\">1746.180</td>\n<td headers=\"stub_1_4 7\" class=\"gt_row gt_right\">1743.146</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_right gt_stub\">4</th>\n<td headers=\"stub_1_5 0\" class=\"gt_row gt_right\">1739.199</td>\n<td headers=\"stub_1_5 1\" class=\"gt_row gt_right\">1741.148</td>\n<td headers=\"stub_1_5 2\" class=\"gt_row gt_right\">1743.143</td>\n<td headers=\"stub_1_5 3\" class=\"gt_row gt_right\">1739.524</td>\n<td headers=\"stub_1_5 4\" class=\"gt_row gt_right\">1744.779</td>\n<td headers=\"stub_1_5 5\" class=\"gt_row gt_right\">1746.982</td>\n<td headers=\"stub_1_5 6\" class=\"gt_row gt_right\">1748.500</td>\n<td headers=\"stub_1_5 7\" class=\"gt_row gt_right\">1742.611</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_right gt_stub\">5</th>\n<td headers=\"stub_1_6 0\" class=\"gt_row gt_right\">1741.137</td>\n<td headers=\"stub_1_6 1\" class=\"gt_row gt_right\">1743.129</td>\n<td headers=\"stub_1_6 2\" class=\"gt_row gt_right\">1745.129</td>\n<td headers=\"stub_1_6 3\" class=\"gt_row gt_right\">1741.195</td>\n<td headers=\"stub_1_6 4\" class=\"gt_row gt_right\">1745.767</td>\n<td headers=\"stub_1_6 5\" class=\"gt_row gt_right\">1748.707</td>\n<td headers=\"stub_1_6 6\" class=\"gt_row gt_right\">1747.336</td>\n<td headers=\"stub_1_6 7\" class=\"gt_row gt_right\">1745.710</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_right gt_stub\">6</th>\n<td headers=\"stub_1_7 0\" class=\"gt_row gt_right\">1743.118</td>\n<td headers=\"stub_1_7 1\" class=\"gt_row gt_right\">1743.277</td>\n<td headers=\"stub_1_7 2\" class=\"gt_row gt_right\">1745.380</td>\n<td headers=\"stub_1_7 3\" class=\"gt_row gt_right\">1746.631</td>\n<td headers=\"stub_1_7 4\" class=\"gt_row gt_right\">1748.622</td>\n<td headers=\"stub_1_7 5\" class=\"gt_row gt_right\">1750.492</td>\n<td headers=\"stub_1_7 6\" class=\"gt_row gt_right\">1750.047</td>\n<td headers=\"stub_1_7 7\" class=\"gt_row gt_right\">1745.446</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_right gt_stub\">7</th>\n<td headers=\"stub_1_8 0\" class=\"gt_row gt_right\">1744.801</td>\n<td headers=\"stub_1_8 1\" class=\"gt_row gt_right\">1745.010</td>\n<td headers=\"stub_1_8 2\" class=\"gt_row gt_right\">1747.007</td>\n<td headers=\"stub_1_8 3\" class=\"gt_row gt_right\">1745.080</td>\n<td headers=\"stub_1_8 4\" class=\"gt_row gt_right\">1746.984</td>\n<td headers=\"stub_1_8 5\" class=\"gt_row gt_right\">1750.945</td>\n<td headers=\"stub_1_8 6\" class=\"gt_row gt_right\">1752.307</td>\n<td headers=\"stub_1_8 7\" class=\"gt_row gt_right\">1747.128</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nTherefore, we fit the following AR(1) model to $\\nu_t=0.1690(0.03277) \\nu_{t-1}+ \\epsilon_t$, which was significant to at least the 95% confidence level (output table available in appendix). Then the final model is a time-trend model with ARMA(1, 0) residuals:\n\n$$\n\\begin{aligned}\nz_t= 3.5402 (0.1191)- 0.7205 (0.0811) Sat - 1.2200 (0.0768) Sun + 0.3285 (0.0692) \\text{Thu-Fri} \\\\\n+ 0.2291 (0.0732) \\text{Tue-Wed}+0.4536 (0.1046) \\text{Apr-May}+0.3564 (0.1048) \\text{Aug-Oct} \\\\ \n+0.1505 (0.1833) \\text{Dec} + 0.1832 (0.1215) \\text{Feb}+0.4917 (0.1013) \\text{Jul} \\\\\n + 0.3640 (0.1316) \\text{Jun}+0.3702 (0.1218) \\text{Mar}+0.1801 (0.1259) \\text{Nov} \\\\\n -1.9650 (0.1148) \\text{Public and School Holiday}-1.9895 (0.2405) \\text{Public Holiday} \\\\\n -0.5674 (0.0821) \\text{School Holiday} +  0.1692 (0.0328) \\nu_{t-1} + \\epsilon_t\n\\end{aligned}\n$${#eq-M4}\n\nAgain, there isn’t any additional interpretation outside of the time-trend model besides saying that the structure of the error of the time-trend model follows an autoregressive AR(1) pattern.\n\n## Seasonal ARIMA Model of $Z_t$\n\nWe appear to have quite successfully fit two time-trend models. Let’s see if a Seasonal Autoregressive Integrated Moving Average (SARIMA or Seasonal ARIMA) model can outperform these time-trend models. The SARIMA approach has the benefit of being much simpler to fit as less data preprocessing is necessary, and you only need to fit one model. An ARIMA model will not be considered, as there is clear evidence of seasonality in the dataset. Analysis procedure here based on chapter 8 of forecasting principles and practice version 1[8]. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nFrom the plots of $z_t$, we see that the mean appears to be stationary but there is evidence of seasonality. The ACF shows spikes at lag 6 and the PACF shows also spikes at lag 7, that decay to 0. This is evidence of weekly seasonality; therefore, we take a seasonal difference of 7 and then analyse $z_t-z_(t-7)$. This plot shows a spike in the ACF at lag 7 only and decaying spikes in the PACF at 7, this indicates that we have somewhat dealt with the seasonality by differencing. There is no evidence of a trend so $d = D = 0$. The seasonally differenced ACF plot also indicates a $MA(1)_7$ trend and the PACF has a positive spike at lag 1 and the ACF has a spike at 1 which signals an ARMA(1, 1) in the non-seasonal part of the model. Therefore we start by fitting the following model: $\\text{SARIMA}(1,0,1)(0,0,1)_7$ model. Models are iteratively fit adding orders based on the ACF and PACF plots those plots show stationarity. We finally end up with a $\\text{SARIMA}(2,0,1)(1,0,1)_7$ model after some other excluded intermediate steps.  The estimation is done with an CSS-ML method.\n\n\n::: callout-note\n## Time Series Display for SARIMA Model Building Process (optional)\n<details>\n<summary>Click to expand time series diagnostic display</summary>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-15-3.png){width=672}\n:::\n:::\n\n\n</details>\n:::\n\n\n\n::: {#tbl-sarima-aic .cell tbl-cap='AIC of Various SARIMA models'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"irhmrircqv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#irhmrircqv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#irhmrircqv thead, #irhmrircqv tbody, #irhmrircqv tfoot, #irhmrircqv tr, #irhmrircqv td, #irhmrircqv th {\n  border-style: none;\n}\n\n#irhmrircqv p {\n  margin: 0;\n  padding: 0;\n}\n\n#irhmrircqv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#irhmrircqv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#irhmrircqv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#irhmrircqv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#irhmrircqv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#irhmrircqv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#irhmrircqv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#irhmrircqv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#irhmrircqv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#irhmrircqv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#irhmrircqv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#irhmrircqv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#irhmrircqv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#irhmrircqv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#irhmrircqv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irhmrircqv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#irhmrircqv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#irhmrircqv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#irhmrircqv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irhmrircqv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#irhmrircqv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irhmrircqv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#irhmrircqv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irhmrircqv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#irhmrircqv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irhmrircqv .gt_left {\n  text-align: left;\n}\n\n#irhmrircqv .gt_center {\n  text-align: center;\n}\n\n#irhmrircqv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#irhmrircqv .gt_font_normal {\n  font-weight: normal;\n}\n\n#irhmrircqv .gt_font_bold {\n  font-weight: bold;\n}\n\n#irhmrircqv .gt_font_italic {\n  font-style: italic;\n}\n\n#irhmrircqv .gt_super {\n  font-size: 65%;\n}\n\n#irhmrircqv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#irhmrircqv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#irhmrircqv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#irhmrircqv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#irhmrircqv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#irhmrircqv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#irhmrircqv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#irhmrircqv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#irhmrircqv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ARIMA(1,0,1)(0,0,1)[7]\">ARIMA(1,0,1)(0,0,1)[7]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ARIMA(1,0,1)(1,0,1)[7]\">ARIMA(1,0,1)(1,0,1)[7]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ARIMA(2,0,1)(1,0,1)[7]\">ARIMA(2,0,1)(1,0,1)[7]</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">AIC</th>\n<td headers=\"stub_1_1 ARIMA(1,0,1)(0,0,1)[7]\" class=\"gt_row gt_right\">2275.244</td>\n<td headers=\"stub_1_1 ARIMA(1,0,1)(1,0,1)[7]\" class=\"gt_row gt_right\">1996.153</td>\n<td headers=\"stub_1_1 ARIMA(2,0,1)(1,0,1)[7]\" class=\"gt_row gt_right\" style=\"background-color: #00FF00; font-weight: bold;\">1990.924</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nLet’s now fit and estimate this model, note we will use a mean as there is no time trend part.\n\n\n\n::: {#tbl-sarima-est .cell tbl-cap='Estimates for the SARIMA(2,0,1)(1,0,1)[7] model'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gygyzntvgy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gygyzntvgy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gygyzntvgy thead, #gygyzntvgy tbody, #gygyzntvgy tfoot, #gygyzntvgy tr, #gygyzntvgy td, #gygyzntvgy th {\n  border-style: none;\n}\n\n#gygyzntvgy p {\n  margin: 0;\n  padding: 0;\n}\n\n#gygyzntvgy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gygyzntvgy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gygyzntvgy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gygyzntvgy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gygyzntvgy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gygyzntvgy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gygyzntvgy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gygyzntvgy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gygyzntvgy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gygyzntvgy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gygyzntvgy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gygyzntvgy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gygyzntvgy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gygyzntvgy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gygyzntvgy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gygyzntvgy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gygyzntvgy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gygyzntvgy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gygyzntvgy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gygyzntvgy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gygyzntvgy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gygyzntvgy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gygyzntvgy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gygyzntvgy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gygyzntvgy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gygyzntvgy .gt_left {\n  text-align: left;\n}\n\n#gygyzntvgy .gt_center {\n  text-align: center;\n}\n\n#gygyzntvgy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gygyzntvgy .gt_font_normal {\n  font-weight: normal;\n}\n\n#gygyzntvgy .gt_font_bold {\n  font-weight: bold;\n}\n\n#gygyzntvgy .gt_font_italic {\n  font-style: italic;\n}\n\n#gygyzntvgy .gt_super {\n  font-size: 65%;\n}\n\n#gygyzntvgy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gygyzntvgy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gygyzntvgy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gygyzntvgy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gygyzntvgy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gygyzntvgy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gygyzntvgy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gygyzntvgy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gygyzntvgy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.values\">p.values</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">ar1</th>\n<td headers=\"stub_1_1 estimate\" class=\"gt_row gt_right\">1.0719</td>\n<td headers=\"stub_1_1 se\" class=\"gt_row gt_right\">0.0681</td>\n<td headers=\"stub_1_1 p.values\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">ar2</th>\n<td headers=\"stub_1_2 estimate\" class=\"gt_row gt_right\">-0.1356</td>\n<td headers=\"stub_1_2 se\" class=\"gt_row gt_right\">0.0479</td>\n<td headers=\"stub_1_2 p.values\" class=\"gt_row gt_right\">0.0047</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">ma1</th>\n<td headers=\"stub_1_3 estimate\" class=\"gt_row gt_right\">-0.8023</td>\n<td headers=\"stub_1_3 se\" class=\"gt_row gt_right\">0.0569</td>\n<td headers=\"stub_1_3 p.values\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">sar1</th>\n<td headers=\"stub_1_4 estimate\" class=\"gt_row gt_right\">0.9999</td>\n<td headers=\"stub_1_4 se\" class=\"gt_row gt_right\">0.0001</td>\n<td headers=\"stub_1_4 p.values\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">sma1</th>\n<td headers=\"stub_1_5 estimate\" class=\"gt_row gt_right\">-0.9909</td>\n<td headers=\"stub_1_5 se\" class=\"gt_row gt_right\">0.0077</td>\n<td headers=\"stub_1_5 p.values\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">intercept</th>\n<td headers=\"stub_1_6 estimate\" class=\"gt_row gt_right\">3.5252</td>\n<td headers=\"stub_1_6 se\" class=\"gt_row gt_right\">0.6571</td>\n<td headers=\"stub_1_6 p.values\" class=\"gt_row gt_right\">0.0000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\n\\begin{aligned}\nz_t = 1.0719 z_{t-1}-0.1356 z_{t-2}+0.9999 z_{t-7}-1.0717 z_{t-8} \\\\\n+0.1355z_{t-9}+3.5252+ \\epsilon_t-0.8023 \\epsilon_{t-1}+0.9909 \\epsilon_{t-7}-0.7951 \\epsilon_{t-8}\n\\end{aligned}\n$${#eq-M5}\n\nAll coefficients are significant to at least a 95% confidence level, see appendix for full model output. Interpreting this model, we find that the current value of $z_t$ is positively correlated with the past value and has a much smaller negative correlation with lag 2. Large values of crashes from the previous week have a positive correlation with the current number of ACT road rashes, which signals strong weekly seasonality. The baseline average for $z_t$ is $3.5252$. Any past innovations to the model (i.e. $\\epsilon$) at lag 1, smooth out the current forecast and an innovation from the past week increases the current estimate, but the following day this is again smoothed out by the lag 8 shock. So, these lagged innovations tend to smooth out the predictions of $z_t$.\n\n\n## Seasonal Auto ARIMA Model of $z_t$\n\nWhilst the SARIMA process above found a reasonable model, there may be a better choice using an `auto.arima` procedure. Therefore, lets run `auto.arima` on the non-stabilised z_t to see how it performs. Because of apparent strong weekly seasonality, we will let the `auto.arima` find a model with weekly seasonality. The max $p$ and $q$ and order will be set to 7 and seasonality will be set to true. This selects a SARIMA model of order $(1,0,0) (2,0,0)_7$, and it is estimated as:\n\n\n::: {#tbl-auto-model .cell tbl-cap='Estimate for Seasonal Auto ARIMA Model'}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Fitting models using approximations to speed things up...\n\n ARIMA(2,0,2)(1,0,1)[7] with non-zero mean : Inf\n ARIMA(0,0,0)           with non-zero mean : 2511.667\n ARIMA(1,0,0)(1,0,0)[7] with non-zero mean : 2218.862\n ARIMA(0,0,1)(0,0,1)[7] with non-zero mean : 2279.094\n ARIMA(0,0,0)           with zero mean     : 4955.047\n ARIMA(1,0,0)           with non-zero mean : 2364.57\n ARIMA(1,0,0)(2,0,0)[7] with non-zero mean : 2159.634\n ARIMA(1,0,0)(2,0,1)[7] with non-zero mean : Inf\n ARIMA(1,0,0)(1,0,1)[7] with non-zero mean : Inf\n ARIMA(0,0,0)(2,0,0)[7] with non-zero mean : 2235.562\n ARIMA(2,0,0)(2,0,0)[7] with non-zero mean : 2160.536\n ARIMA(1,0,1)(2,0,0)[7] with non-zero mean : 2160.734\n ARIMA(0,0,1)(2,0,0)[7] with non-zero mean : 2167.306\n ARIMA(2,0,1)(2,0,0)[7] with non-zero mean : 2160.613\n ARIMA(1,0,0)(2,0,0)[7] with zero mean     : Inf\n\n Now re-fitting the best model(s) without approximations...\n\n ARIMA(1,0,0)(2,0,0)[7] with non-zero mean : 2164.89\n\n Best model: ARIMA(1,0,0)(2,0,0)[7] with non-zero mean \n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jxtxzgyhvj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jxtxzgyhvj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jxtxzgyhvj thead, #jxtxzgyhvj tbody, #jxtxzgyhvj tfoot, #jxtxzgyhvj tr, #jxtxzgyhvj td, #jxtxzgyhvj th {\n  border-style: none;\n}\n\n#jxtxzgyhvj p {\n  margin: 0;\n  padding: 0;\n}\n\n#jxtxzgyhvj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jxtxzgyhvj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jxtxzgyhvj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jxtxzgyhvj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jxtxzgyhvj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jxtxzgyhvj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jxtxzgyhvj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jxtxzgyhvj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jxtxzgyhvj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jxtxzgyhvj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jxtxzgyhvj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jxtxzgyhvj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jxtxzgyhvj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jxtxzgyhvj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jxtxzgyhvj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxtxzgyhvj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jxtxzgyhvj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jxtxzgyhvj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jxtxzgyhvj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxtxzgyhvj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jxtxzgyhvj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxtxzgyhvj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jxtxzgyhvj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxtxzgyhvj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxtxzgyhvj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxtxzgyhvj .gt_left {\n  text-align: left;\n}\n\n#jxtxzgyhvj .gt_center {\n  text-align: center;\n}\n\n#jxtxzgyhvj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jxtxzgyhvj .gt_font_normal {\n  font-weight: normal;\n}\n\n#jxtxzgyhvj .gt_font_bold {\n  font-weight: bold;\n}\n\n#jxtxzgyhvj .gt_font_italic {\n  font-style: italic;\n}\n\n#jxtxzgyhvj .gt_super {\n  font-size: 65%;\n}\n\n#jxtxzgyhvj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jxtxzgyhvj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jxtxzgyhvj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jxtxzgyhvj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jxtxzgyhvj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jxtxzgyhvj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jxtxzgyhvj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jxtxzgyhvj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jxtxzgyhvj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.values\">p.values</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">ar1</th>\n<td headers=\"stub_1_1 estimate\" class=\"gt_row gt_right\">0.2947</td>\n<td headers=\"stub_1_1 se\" class=\"gt_row gt_right\">0.0323</td>\n<td headers=\"stub_1_1 p.values\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">sar1</th>\n<td headers=\"stub_1_2 estimate\" class=\"gt_row gt_right\">0.2925</td>\n<td headers=\"stub_1_2 se\" class=\"gt_row gt_right\">0.0326</td>\n<td headers=\"stub_1_2 p.values\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">sar2</th>\n<td headers=\"stub_1_3 estimate\" class=\"gt_row gt_right\">0.2584</td>\n<td headers=\"stub_1_3 se\" class=\"gt_row gt_right\">0.0323</td>\n<td headers=\"stub_1_3 p.values\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">intercept</th>\n<td headers=\"stub_1_4 estimate\" class=\"gt_row gt_right\">3.5296</td>\n<td headers=\"stub_1_4 se\" class=\"gt_row gt_right\">0.0813</td>\n<td headers=\"stub_1_4 p.values\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\nz_t=0.2947z_{t-1}+0.2925z_{t-7}+0.2584z_{t-14}+3.5296+ \\epsilon_t\n$$ {#eq-M6}\n\nThis is an odd choice by the `auto.arima` function as the residuals of this model (available in the appendix) show evidence of serial autocorrelation. All coefficients are marginally significant to at least a 95% confidence level. This model simply says that the square root of the number of ACT road crashes has a baseline of $3.5396$ and nearly equally related to the past values at lags 1, 7 and 8. Perhaps this simpler model will result in test predictions than the more flexible previously fit SARIMA model.\n\n::: callout-note\n## Time Series Display for Seasonal Auto ARIMA Model Building Process (optional)\n<details>\n<summary>Click to expand time series diagnostic display</summary>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](forecastCrashes_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n</details>\n:::\n\n# Model Diagnostics\n\nPerform residual diagnostics to determine if the model from part 3 were adequately fit. Whilst I will consider outliers, no attempt will be made to assess high influence observations as cook’s distance is not valid with dependent error structures.\n\n## Time Trend with ARMA(0, 1) Residuals (SEACF)\n\n\n::: {.cell}\n\n:::\n\n\n::: callout-note\n\n## Residual Diagnostic Plots for Time Trend Model with ARMA(0, 1) (optional)\n<details>\n<summary>Click to expand</summary>\n\n\n::: {#fig-res-arma01 .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Residual Plots](forecastCrashes_files/figure-html/fig-res-arma01-1.png){#fig-res-arma01-1 width=672}\n:::\n\n::: {.cell-output-display}\n![QQ Plot](forecastCrashes_files/figure-html/fig-res-arma01-2.png){#fig-res-arma01-2 width=672}\n:::\n\nResidual Diagnostic Plots for Time Trend Model with ARMA(0, 1)\n:::\n\n\n</details>\n:::\n\n\nExamining the model diagnostics, we find the residuals do appear scattered around 0 with somewhat consistent variance around 0, which meets the linearity of errors and homoscedasticity assumptions. There does not appear to be any omitted variable bias. Furthermore, the variance assumption is met decently until the top part of the distribution which is a little heavy tailed. Given the amount of data though we shouldn't be too concerned as the CLT will help ensure that a slight variation of this isn't too problematic. Finally, the Ljung-Box test passes as no p-values cross the 0.05 threshold, signalling that there is no evidence of dependence of observations. This model has 7 outliers with absolute standardized residual greater than 3, this is on par given the number of observations we have. The outliers tend to be either school holidays or days in the middle of the week. Overall, we cannot remove these residuals but maybe there is some difference in traffic on  certain school holidays that could be better accounted for.  Overall, there is no evidence to suggest that this model egregiously violates the model diagnostics.\n\n## Time Trend with ARMA(1, 0) Residuals (AIC)\n\n::: callout-note\n## Residual Diagnostic Plots for Time Trend Model with ARMA(1, 0) (optional)\n<details>\n<summary>Click to expand</summary>\n\n\n::: {#fig-res-arma10 .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Residual Plots](forecastCrashes_files/figure-html/fig-res-arma10-1.png){#fig-res-arma10-1 width=672}\n:::\n\n::: {.cell-output-display}\n![QQ Plot](forecastCrashes_files/figure-html/fig-res-arma10-2.png){#fig-res-arma10-2 width=672}\n:::\n\nResidual Diagnostic Plots for Time Trend Model with ARMA(1, 0)\n:::\n\n\n</details>\n:::\n\n\nThe constant variance and linearity of residuals assumptions are met for this model. There does not appear to be any omitted variable bias. Similarly to the previous model, the residuals are mostly normal with a slightly heavy right tail. This makes the trend in the residuals sense given that that $z_t$ is slightly right skewed. Again the Ljung-Box test passes, so there is no evidence of serial autocorrelation of the errors of the model. There are, similarly to the past time-trend ARMA(0, 1) model 7 outliers, which occur  Tuesday-Friday or on a school holiday. Therefore, the residuals of this model are stationary and overall, the assumptions of the model do not appear to be violated. \n\n## Seasonal ARIMA Model of $z_t$ $\\text{SARIMA}(2,0,1) (1,0,1)_7$\n\n\n::: callout-note\n## Residual Diagnostic Plots for Seasonal ARIMA Model $\\text{SARIMA}(2,0,1) (1,0,1)_7$ (optional)\n<details>\n<summary>Click to expand</summary>\n\n\n::: {#fig-res-sarima .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Residual Plots](forecastCrashes_files/figure-html/fig-res-sarima-1.png){#fig-res-sarima-1 width=672}\n:::\n\n::: {.cell-output-display}\n![QQ Plot](forecastCrashes_files/figure-html/fig-res-sarima-2.png){#fig-res-sarima-2 width=672}\n:::\n\nResidual Diagnostic Plots for Seasonal ARIMA Model SARIMA(2,0,1) (1,0,1)[7]\n:::\n\n\n\n</details>\n:::\n\nNo issue with the constant variance assumption or linearity assumption. There does not appear to be any omitted variable bias. The QQ-plot shows slightly heavy bottom tail, but overall the residuals are normal. The Box-Ljung test finds no evidence of serial dependence of errors, so there is no evidence that the dependence of errors assumption is violated. Note, whilst we cannot remove outliers there are 9 outliers with a absolute standardized residual greater than 3. All but one of these outliers occur on a public holiday, most occur during a midweek public holiday. The non-public holiday outlier occurs on Wednesday 2017-04-26, on this date there were school and public holidays on Monday and Tuesday and Wednesday would have been the first day back at school. This likely caused a higher-than-expected number of road accidents as the day following a weekend tends to have the highest accident rate. However, given that it looks like a one off, and you cannot remove time series outliers, I will not attempt to control for this point. This indicates that the SARIMA model is failing to accurately predict the surge in crashes on a public holiday, which the time-trend models are capable of predicting. This highlights one of the downsides of the SARIMA approach, we cannot account for these intermittent events. Overall, none of the model assumptions are violated other than perhaps a slight violation of omitted variable bias. Seasonal Auto ARIMA Model of $z_t$ $\\text{SARIMA}(1,0,0) (2,0,0)_7$.\n\n## Auto SARIMA model $\\text{SARIMA}(1,0,0)(2,0,0)_7$\n\n::: callout-note\n## Residual Diagnostic Plots for Seasonal ARIMA Model $\\text{SARIMA}(1,0,0)(2,0,0)_7$ (optional)\n<details>\n<summary>Click to expand</summary>\n\n\n::: {#fig-res-auto-sarima .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Residual Plots](forecastCrashes_files/figure-html/fig-res-auto-sarima-1.png){#fig-res-auto-sarima-1 width=672}\n:::\n\n::: {.cell-output-display}\n![QQ Plot](forecastCrashes_files/figure-html/fig-res-auto-sarima-2.png){#fig-res-auto-sarima-2 width=672}\n:::\n\nResidual Diagnostic Plots for Seasonal ARIMA Model SARIMA(1,0,0)(2,0,0)[7]\n:::\n\n</details>\n:::\n\n\nAgain, no issues with the constant variance assumption or linearity of assumption, however the residuals do not appear to be random scatter and hint at some pattern. The residuals look very normal, some tiny amount of light tails at the bottom of the distribution but overall the residuals are sufficiently normal. However, this fails the Box-Ljung test, indicating serial autocorrelation. The ACF plot shows persistent autocorrelation with lags 5, 10, 15 and so on, which does not decay to 0. Therefore, the auto.arima function selected a model that does not adequately meet the independence of observations assumption. This is a warning that auto.arima on its own is not sufficient to fit models. In addition, there are 5 outliers (absolute standardized residual greater than 3) which include the date 2017-04-26 (discussed previously) and 4 public holidays that occur on a Friday. Again, indicating that the SARIMA model fails to adequately fit some of the public holidays. \n\n# Data Prediction for Training Test Split\n\nTo assess the accuracy of the fitted models, use the $MSEP^{(T')}$, which is the Mean Square Error of Prediction (MSEP) for the truncated one-step-ahead forecast for time $T+1,T+2, \\ldots, T'-1, T'$. The $MSEP^{(T' )}$ is calcuated as:\n\n$$\nMSEP^{(T')}=  \\frac{1}{T'} \\sum_{j = 1}^{T'} (y_{T + j}  - \\widehat{y_{T+j|T}})\n$$\n\nIn addition to the four models fitted and diagnosed, I will also include a Naive estimate. This is just the last value from the training time series at time $T$,$y_T.$ Ideally, a good model would have a smaller prediction than this naive baseline. \n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-pred .cell tbl-cap='Mean Squared Error of Prediction for all models trained on 1, ..., T predicting T + 1 to T\\''}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"umlqvuzmri\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#umlqvuzmri table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#umlqvuzmri thead, #umlqvuzmri tbody, #umlqvuzmri tfoot, #umlqvuzmri tr, #umlqvuzmri td, #umlqvuzmri th {\n  border-style: none;\n}\n\n#umlqvuzmri p {\n  margin: 0;\n  padding: 0;\n}\n\n#umlqvuzmri .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#umlqvuzmri .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#umlqvuzmri .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#umlqvuzmri .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#umlqvuzmri .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#umlqvuzmri .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#umlqvuzmri .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#umlqvuzmri .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#umlqvuzmri .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#umlqvuzmri .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#umlqvuzmri .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#umlqvuzmri .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#umlqvuzmri .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#umlqvuzmri .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#umlqvuzmri .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umlqvuzmri .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#umlqvuzmri .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#umlqvuzmri .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#umlqvuzmri .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umlqvuzmri .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#umlqvuzmri .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umlqvuzmri .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#umlqvuzmri .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umlqvuzmri .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#umlqvuzmri .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umlqvuzmri .gt_left {\n  text-align: left;\n}\n\n#umlqvuzmri .gt_center {\n  text-align: center;\n}\n\n#umlqvuzmri .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#umlqvuzmri .gt_font_normal {\n  font-weight: normal;\n}\n\n#umlqvuzmri .gt_font_bold {\n  font-weight: bold;\n}\n\n#umlqvuzmri .gt_font_italic {\n  font-style: italic;\n}\n\n#umlqvuzmri .gt_super {\n  font-size: 65%;\n}\n\n#umlqvuzmri .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#umlqvuzmri .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#umlqvuzmri .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#umlqvuzmri .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#umlqvuzmri .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#umlqvuzmri .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#umlqvuzmri .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#umlqvuzmri .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#umlqvuzmri div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"naive\">naive</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time-Trend-ARMA(0,-1)\">Time-Trend ARMA(0, 1)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time-Trend-ARMA(1,-0)\">Time-Trend ARMA(1, 0)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SARIMA(2,-0,-1)(1,-0,-1)[7]\">SARIMA(2, 0, 1)(1, 0, 1)[7]</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Auto-SARIMA(1,-0,-0)(2,-0,-0)[7]\">Auto SARIMA(1, 0, 0)(2, 0, 0)[7]</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">MSEP^(T')</th>\n<td headers=\"stub_1_1 naive\" class=\"gt_row gt_right\">66.9222</td>\n<td headers=\"stub_1_1 Time-Trend ARMA(0, 1)\" class=\"gt_row gt_right\">30.5839</td>\n<td headers=\"stub_1_1 Time-Trend ARMA(1, 0)\" class=\"gt_row gt_right\">30.5834</td>\n<td headers=\"stub_1_1 SARIMA(2, 0, 1)(1, 0, 1)[7]\" class=\"gt_row gt_right\">42.2337</td>\n<td headers=\"stub_1_1 Auto SARIMA(1, 0, 0)(2, 0, 0)[7]\" class=\"gt_row gt_right\">65.8764</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n \nIn terms of $MSEP^{(T^')}$, the most accurate model is the Time-Trend ARMA(1,0) model (fit using AIC method) that marginally beats out the other Time-Trend. In truth, the accuracy between the two time trend models is nearly indistinguishable, which makes sense as the ARMA errors are only different for the first few time points then decay quickly to the mean. Notably, the Time-Trend model performs more than twice as good compared to a Naïve predictor.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model Test Prediction vs Actual](forecastCrashes_files/figure-html/fig-pred-1.png){#fig-pred width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model Test Prediction vs Actual for First 4 Weeks](forecastCrashes_files/figure-html/fig-pred-4weeks-1.png){#fig-pred-4weeks width=672}\n:::\n:::\n\n\nThe required time series graph is a little difficult to interpret given the large number of data points so, an additional graph only looking at the first 28 days was included. The graph shows that neither of the time-trend models (aka SEACF or AIC) have an indistinguishable fit. The AIC and SEACF time-trend models appear to most accurately follow the peaks and troughs of the actual trend however, the SARIMA model also appears to do a decent job. The Auto Sarima model is too smoothed and appears to underfit the peaks and troughs of the data. This is the same conclusion as the $MSEP^{(T')}$ which makes sense as the accuracy measure is the mean squared distance to the true point. $MSEP^{(T')}$ can be inaccurate however when there are lots of large outliers, so the $MSEP^{(T')}$. In our case however, we didn’t see more than 10 outliers for either trend, so it is understandable that $MSEP^{(T')}$ matches the findings of the graph.\n\nAs discussed in the model fitting section there are patterns in the data that the SARIMA models can't pick up. For example, the public holidays are more difficult for the SARIMA model to fit due to changes in calendar and annual changes in public holiday days. In addition, the seasonality being modelled as factors likely provides greater flexibility to the time-trend model, which have19 parameters compared to the largest SARIMA model which has only 9 parameters. Given the large amount of training data this flexibility has likely allowed the bias of the model to be reduced significantly. The performance of the SARIMA models however is impressive given the lack of additional information about public and school holidays. In addition,  the SARIMA model only has the weekly seasonality, it doesn't consider the monthly seasonality the time-trend models do.\n\nComparing the models, the auto SARIMA had the worst regression diagnostics and by far had the worst accuracy. This is likely as there was something in our model that the diagnostics is telling us it is missing. However, for the models that passed the diagnostics there is no indication which of these three models would fit better. Therefore, the diagnostics were useful in indicating that the model that failed the diagnostics was a poor predictor but, it was not useful in distinguishing the predictive ability of those that passed.\n\n\n\n# Rolling Window Prediction\n\nThe rolling window procedure estimates the one-step-ahead forecast for each point in the test dataset using the orders and parameters selected from the test dataset. Accuracy will then be measure as \n\n$$\nMSEP_1= \\frac{1}{T'} \\sum_{t = T}^{T+T'-1} (y_{t + 1}- \\widehat{y_{t+1|S_t}}) \n$$ {#eq-msep-roll}\n\nHowever, the coefficient estimates in the linear regression, ARMA, and SARIMA models are computed using the window of observations proceeding the observation being predicting (including test data that proceeds the time being predicted). A slight alteration was made to my window sizes as the time-trend models need approximately 365 days of data to fit the monthly seasonality. As a result, I will use floor or $0.37$, $b_{0.37} = 337$ and floor of $0.74$, $b_{0.64} = 674$. This gives us two more evenly spaced samples for comparison and enough data for the model to be fit. The Naive estimator for the rolling window predictor is previous observations, this is used for comparison purposes.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n \n\n::: {.cell}\n\n:::\n\n\n\n\n::: {#tbl-rolling .cell tbl-cap='MSEP for the Rolling Winodw Prediction Models'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"plsqmqofjh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#plsqmqofjh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#plsqmqofjh thead, #plsqmqofjh tbody, #plsqmqofjh tfoot, #plsqmqofjh tr, #plsqmqofjh td, #plsqmqofjh th {\n  border-style: none;\n}\n\n#plsqmqofjh p {\n  margin: 0;\n  padding: 0;\n}\n\n#plsqmqofjh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#plsqmqofjh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#plsqmqofjh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#plsqmqofjh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#plsqmqofjh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#plsqmqofjh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#plsqmqofjh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#plsqmqofjh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#plsqmqofjh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#plsqmqofjh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#plsqmqofjh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#plsqmqofjh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#plsqmqofjh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#plsqmqofjh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#plsqmqofjh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plsqmqofjh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#plsqmqofjh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#plsqmqofjh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#plsqmqofjh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plsqmqofjh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#plsqmqofjh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plsqmqofjh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#plsqmqofjh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plsqmqofjh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plsqmqofjh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plsqmqofjh .gt_left {\n  text-align: left;\n}\n\n#plsqmqofjh .gt_center {\n  text-align: center;\n}\n\n#plsqmqofjh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#plsqmqofjh .gt_font_normal {\n  font-weight: normal;\n}\n\n#plsqmqofjh .gt_font_bold {\n  font-weight: bold;\n}\n\n#plsqmqofjh .gt_font_italic {\n  font-style: italic;\n}\n\n#plsqmqofjh .gt_super {\n  font-size: 65%;\n}\n\n#plsqmqofjh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#plsqmqofjh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#plsqmqofjh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#plsqmqofjh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#plsqmqofjh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#plsqmqofjh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#plsqmqofjh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#plsqmqofjh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#plsqmqofjh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"naive\">naive</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time-Trend-ARMA(0,-1)\">Time-Trend ARMA(0, 1)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time-Trend-ARMA(1,-0)\">Time-Trend ARMA(1, 0)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SARIMA(2,-0,-1)(1,-0,-1)[7]*\">SARIMA(2, 0, 1)(1, 0, 1)[7]*</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Auto-SARIMA(1,-0,-0)(2,-0,-0)[7]\">Auto SARIMA(1, 0, 0)(2, 0, 0)[7]</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">MSEP^(T')</th>\n<td headers=\"stub_1_1 naive\" class=\"gt_row gt_right\">66.9222</td>\n<td headers=\"stub_1_1 Time-Trend ARMA(0, 1)\" class=\"gt_row gt_right\">30.5839</td>\n<td headers=\"stub_1_1 Time-Trend ARMA(1, 0)\" class=\"gt_row gt_right\">30.5834</td>\n<td headers=\"stub_1_1 SARIMA(2, 0, 1)(1, 0, 1)[7]*\" class=\"gt_row gt_right\">42.2337</td>\n<td headers=\"stub_1_1 Auto SARIMA(1, 0, 0)(2, 0, 0)[7]\" class=\"gt_row gt_right\">65.8764</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">MSPE_1  with b_0.37=337</th>\n<td headers=\"stub_1_2 naive\" class=\"gt_row gt_right\">88.7996</td>\n<td headers=\"stub_1_2 Time-Trend ARMA(0, 1)\" class=\"gt_row gt_right\">34.1866</td>\n<td headers=\"stub_1_2 Time-Trend ARMA(1, 0)\" class=\"gt_row gt_right\">34.1720</td>\n<td headers=\"stub_1_2 SARIMA(2, 0, 1)(1, 0, 1)[7]*\" class=\"gt_row gt_right\">53.7847*</td>\n<td headers=\"stub_1_2 Auto SARIMA(1, 0, 0)(2, 0, 0)[7]\" class=\"gt_row gt_right\">46.1355</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">MSPE_1  with b_0.64=674</th>\n<td headers=\"stub_1_3 naive\" class=\"gt_row gt_right\">88.7996</td>\n<td headers=\"stub_1_3 Time-Trend ARMA(0, 1)\" class=\"gt_row gt_right\">30.3368</td>\n<td headers=\"stub_1_3 Time-Trend ARMA(1, 0)\" class=\"gt_row gt_right\">30.3417</td>\n<td headers=\"stub_1_3 SARIMA(2, 0, 1)(1, 0, 1)[7]*\" class=\"gt_row gt_right\">52.6989*</td>\n<td headers=\"stub_1_3 Auto SARIMA(1, 0, 0)(2, 0, 0)[7]\" class=\"gt_row gt_right\">45.7470</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n*&#42The only was to get the SARIMA model to execute was the change the order from SARIMA(2,0,1) (1,0,1)_7 to SARIMA(2,0,1) (0,0,1)_7 as the more complex SARIMA model has non-finite finite-difference value and would not converge to a solution regardless of method used to fit it. The simpler model was fit for comparison purposes however, in some sense the fit was also null as the model failed to converge. Both options will be discussed.*\n\nThe $MSPE_1$ table above shows that the Time-Trend models once again perform by far the best. The difference in performance between the time-trend models again is nearly negligible, which likely indicates that either choice is appropriate, and any difference is down to chance. This time, the auto SARIMA model outperformed the SARIMA model (which also failed to converge with the original order and was altered so it would). It appears that the reduction in training data made the more complex SARIMA model unable to fit and less efficient when it was. \n\nThe larger training windows i.e. $b_{0.64}$, performs better than the smaller window across the board. This makes sense, the smaller the training window the more bias and variance in the prediction, hence the worse the prediction is. The rankings of the models do change for the windowed rolling accuracy measures. The ARMA(0, 1) time trend model is the best for the $b_{0.64}$ window but second best for the $b_{0.37}$. For $MSEP^{(T')}$, the Time-Trend ARMA(1, 0) is marginally more accurate. The reason for this change is essentially the two predictions are the same, this is because most of the variation in the model is predicted by the time-trend portion so the difference in the ARMA(1, 0) or ARMA(0, 1) portion of the model appears to be negligible. Any difference in accuracy between the time-trend models is likely down to chance. In the $MSEP^{(T')}$, the Auto SARIMA model was the worst performer, however, is the second worst by $MSPE_1$ and the SARIMA model appears to be the worst. This is because, it appears that the simpler order of the Auto SARIMA model is better when there is less data to estimate the parameters. In addition, the Auto SARIMA model only needs to predict one step ahead. The m-step truncated prediction, misspecification may add up over time, again potentially favouring a more parsimonious model.\n\nThe conclusions from the diagnostic in section 4 do not support the conclusions here. With less training data the SARIMA model failed to converge on a solution even though it passed regression diagnostic. In addition, the Auto SARIMA model performed reasonably, on par with the performance of the SARIMA model in section 5. For the SARIMA models $MSPE_1$ was better for with more parsimonious models. The time-trend models appear to have performed well again, likely because they are much more capable of capturing the true underlying data generating process. Once last interesting finding is that going from 337 window size to 674 only increase the $MSPE_1$ of Auto SARIMA by ~1.5 whilst the $MSPE_1$ of the Time-Trend models went up by nearly 4. This supports the idea that lower SARIMA models are reasonable, but the performance improvement is more marginal with more data.\n\n\n\n# Limitations\n\nThere were several limitations to the modelling that may have improved the modelling procedure. For the time trend model,  School holidays don’t include private school holidays in the ACT which may underestimate lower traffic flows. In addition, no data is available to understand the holiday making trends of people without kids, which may also affect traffic flow. Potentially, a VARIMA model that had as a predictor the daily traffic flow in Canberra could better capture the variation in persons travelling. In addition, some outliers were observed for higher crashes on the day following a public holiday. This is likely because this becomes the new “Monday” of the week. Further factors could be added into the model to control for this. Furthermore, the Time trend model assumes that the seasonal parameters have a constant association over time, other methods weight the factors such that more recent observed affects have greater weight, which could better reflect changed in effects over time. None of the models account for events such as Summernats or music festivals which could further improve forecast accuracy.\nThe forecast errors were not considered in this analysis. Further analysis should look at the forecast errors and asses a metric like the Pinball Loss to assess the accuracy of the prediction intervals. The SARIMA models only had a weekly difference, but there was some evidence as well of monthly seasonality. A better method would consider this for the SARIMA models; however, calendar differences make yearly or monthly differencing tricky with daily data. The SARIMA models saw large outliers on public holidays, including factor variables in the SARIMA model to adjust for this could lead to large improvements in the accuracy of the SARIMA models. Finally, a key limitation of this model is that we assume that the AFP reported crashes are an accurate reflection of the number of crashes in the ACT. The observed trends for example could be a related to people propensity to report rather than an actual trend in the data.\n\n\n::: {.cell}\n\n:::\n\n- School holidays don't account for private school differences or \n- Noted monday and tuesday public holiday resulted in large outlier, try and control for this\n- Time trend model assumes that the seasonal affects are constant over time - ideally we would use the recent differences \n- Non-linear trends\n- Forecast errors\n- data required for holidays etc.\n- can't do double seasons\n- Another one that is in the text somewhere\n\n\n\n::: {.cell}\n\n:::\n\n\n# Conclusion\n\nThis report fit four time series model to the ACT crash data from 1 January 2015 to 31 December 2019. The best model was found to be a Time-Trend model that fit either ARMA(1, 0) or ARMA(0, 1) errors. Whilst simpler to fit, the SARIMA models were found to less accurate and, in some cases, unable to be fit. Some trends that were discovered in the data is that the most car accidents occur on Mondays. Public Holidays, School Holidays and December sees a marked decrease in the frequency of ACT road crashes.\n\n# Bibliography\n\n[1] https://www.data.act.gov.au/Transport/ACT-Road-Crash-Data/6jn4-m8rx/about_data\n[2] ACT Transport Strategy 2020\n[3] https://files.accesscanberra.act.gov.au/legacy/4188/Crash%20reporting.pdf\n[4] TODO ref for public holidays\n[5] https://actschoolholidays.com.au/past-years/\n[6] https://www.education.act.gov.au/public-school-life/term_dates_and_public_holidays/act-school-terms-dates-and-public-holiday-calendar (Contains historical data on the past dates, chatGPT was used to scrap data from earlier years)\n[7] https://otexts.com/fpp3/\n[8] https://otexts.com/fpp3/arima-r.html\n\n",
    "supporting": [
      "forecastCrashes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}